<script setup lang="ts">
import {
  ArrowUpRight,
  ArrowRight,
  ArrowLeft,
  Check,
  ChevronDown,
  ChevronRight,
  Search,
  ShoppingCart,
  UserRound,
  Wallet,
  Gamepad2,
  Headphones,
  Cpu,
  Monitor,
  Cable,
  Armchair,
  Menu,
  X,
  Heart,
  SlidersHorizontal,
  Package,
  Download,
  LayoutGrid,
  ShieldCheck,
  Truck,
  LogOut,
  Settings,
  CreditCard,
  Keyboard,
  Mouse,
  HelpCircle,
} from '@lucide/vue';
const props = withDefaults(defineProps<{ name: string; size?: number }>(), { size: 22 });
const icons = {
  arrow: ArrowUpRight,
  right: ArrowRight,
  left: ArrowLeft,
  check: Check,
  chevron: ChevronDown,
  next: ChevronRight,
  search: Search,
  cart: ShoppingCart,
  user: UserRound,
  wallet: Wallet,
  gamepad: Gamepad2,
  headphones: Headphones,
  cpu: Cpu,
  monitor: Monitor,
  console: Cable,
  chair: Armchair,
  menu: Menu,
  close: X,
  heart: Heart,
  filter: SlidersHorizontal,
  package: Package,
  download: Download,
  grid: LayoutGrid,
  shield: ShieldCheck,
  truck: Truck,
  logout: LogOut,
  settings: Settings,
  card: CreditCard,
  keyboard: Keyboard,
  mouse: Mouse,
  help: HelpCircle,
};
const icon = computed(() => icons[props.name as keyof typeof icons] || Package);
</script>
<template>
  <component :is="icon" :size="size" :stroke-width="1.7" aria-hidden="true" class="store-icon" />
</template>
